# Generated by Django 6.0.7 on 2026-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id_advertencia', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'advertencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad_asignada', models.CharField(max_length=10)),
                ('fecha_asignacion', models.DateTimeField()),
                ('estado_asignacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'asignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('estado_general', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id_falla', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_falla', models.CharField(max_length=20)),
                ('descripcion_tecnica', models.TextField(blank=True, null=True)),
                ('fecha_deteccion', models.DateTimeField()),
            ],
            options={
                'db_table': 'falla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id_garantia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'garantia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPieza',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'historial_pieza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_ruta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloPieza',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('especificaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modelo_pieza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'pieza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoReparacion',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_esperada', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proceso_reparacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=30)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'recordatorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion_rol', models.TextField(blank=True, null=True)),
                ('estado_rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudReparacion',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('prioridad_usuario', models.CharField(max_length=10)),
                ('fecha_solicitud', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'solicitud_reparacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id_tipo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPieza',
            fields=[
                ('id_tipo_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_pieza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=100)),
                ('salon', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ubicacion',
                'unique_together': {('sede', 'salon')},
            },
        ),
    ]
